# Vault list auto-generated by vagrant.
Creating vault for #
ansible-vault create host_vars/#
Creating vault for auto-generated
ansible-vault create host_vars/auto-generated
Creating vault for host
ansible-vault create host_vars/host
Creating vault for list
ansible-vault create host_vars/list
Creating vault for 192.168.44.32
ansible-vault create host_vars/192.168.44.32
