---
- hosts: all
  tasks:
    - name: install the latest version of Apache
      yum: name=httpd state=latest
      notify:
      - restart httpd
    - name: install the latest version of MySQL
      yum: name=mysql-server state=latest
      notify:
      - restart mysqld

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    - name: restart mysqld
      service: name=mysqld state=restarted
